# import tkinter as tk
# window=tk.Tk()
# window.config(background="lightblue")
# window.geometry("600x700")
# def display():
#     print(var.get())
# var=tk.BooleanVar()
# radio1=tk.Radiobutton(window,text='OPTION 1',variable=var,value=True,command=display)
# radio1.pack()
# radio2=tk.Radiobutton(window,text='OPTION 2',variable=var,value=False,command=display)
# radio2.pack()
# window.mainloop()

# import sqlite3 
# connection=sqlite3.connect("mydatabase.db")
# cursor=connection.cursor()
# # cursor.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE)
# cursor.execute("create table if not exists employee(id int ,name varchar(100),age int,salary integer)")
# # cursor.execute("insert into employee values(1,'jitendra',23,25000)")
# id= int(input("enter id :"))
# name=input("enter name :")
# age=int(input("enter age :"))
# salary=int(input("enter salary :"))
# cursor.execute("insert into employee values(?,?,?,?)",(id,name,age,salary))
# connection.commit()
# connection.close()
# print("database created successfully")

import tkinter as tk
import sqlite3
from tkinter import messagebox
window=tk.Tk()
window.geometry("700x600")
label1=tk.Label(window,text="Enter your name : ",font=("BOLD",25))
label1.place(x=10,y=50)
label2=tk.Label(window,text="Enter your age : ",font=("BOLD",25))
label2.place(x=10,y=100)
label3=tk.Label(window,text="Enter your salary : ",font=("BOLD",25))
label3.place(x=10,y=150)
entry1=tk.Entry(window,font=("BOLD",25),bg='green')
entry1.place(x=250,y=50)
entry2=tk.Entry(window,font=("BOLD",25),bg='green')
entry2.place(x=250,y=100)
entry3=tk.Entry(window,font=("BOLD",25),bg='green')
entry3.place(x=250,y=150)
def save():
    name=entry1.get()
    age=entry2.get()
    salary=entry3.get()
    connection=sqlite3.connect("demo.db")
    cursor=connection.cursor()
    cursor.execute("create table if not exists employees1 (name varchar(20), age int, salary int)")
    cursor.execute("insert into employees1 values(?,?,?)",(name,age,salary))
    connection.commit()
    cursor.close()
    connection.close()
    messagebox.showinfo("success","record inserted...")
button=tk.Button(window,text='submit',font=("BOLD",30),bg='red',command=save)
button.place(x=200,y=30)
window.mainloop()